title: Lytain's Blog
root: 我的博客 # 选择`content`文件夹下的一个文件或目录作为`/`路径的页面
defaultLanguage: en # 文件后缀没有指明语言时默认使用的语言
repo: 'https://github.com/Lytain/Lytain.github.io' # github repo address
email: 'lytain2020@gmail.com' # author email address
author: 'Lytain' # author github username
folderIcon: mdi-folder-outline # mdi icon name
fileIcon: mdi-file # mdi icon name
orderDecider: '@' # 用来确定内容顺序
headScripts: # to append custom scripts
  - src: https://www.googletagmanager.com/gtag/js?id=UA-137885294-1
    async: true
  - innerHTML: |
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-137885294-1');
friends:
  - title: 极术社区/jishu
    url: https://aijishu.com
    description: 芯片、AI与嵌入式等学习社区
  - title: 我的空间/ys168
    url: http://lytain.ys168.com
    description: 自己整理和使用的一个学习空间
  - title: 吾爱破解/52pojie
    url: https://www.52pojie.cn
    description: 非常有趣的野生软件、技术
  - title: Xilinx中文/chinaxilinx
    url: https://china.xilinx.com
    description: Xilinx官方社区，最新资料获得
  - title: 迪芝伦中文/digilent
    url: http://www.digilent.com.cn
    description: digilent官方社区，项目与开发
friendsIcon: mdi-open-in-new